/**
 * Email Template Type
 *
 * Represents the style/source of an email template:
 * - FORMAL: Professional, structured tone
 * - CASUAL: Friendly, conversational tone
 * - CUSTOM: User-created custom template
 * - AI_GENERATED: Generated by AI based on contact context
 * - TEMPLATE_BASED: Based on saved user template
 */
export enum TemplateType {
  FORMAL = 'FORMAL',
  CASUAL = 'CASUAL',
  CUSTOM = 'CUSTOM',
  AI_GENERATED = 'AI_GENERATED',
  TEMPLATE_BASED = 'TEMPLATE_BASED',
}
