export { GenerateEmailInput } from './generate-email.input';
export { SaveEmailInput } from './save-email.input';
export { UpdateEmailInput } from './update-email.input';
export { FindEmailsInput } from './find-emails.input';
export { CreateEmailTemplateInput } from './create-email-template.input';
export { UpdateEmailTemplateInput } from './update-email-template.input';
export { CreateConversationEntryInput } from './create-conversation-entry.input';
export { CreateDraftInput } from './create-draft.input';
export { UpdateDraftInput } from './update-draft.input';
export { CreateSignatureInput } from './create-signature.input';
export { UpdateSignatureInput } from './update-signature.input';
export { SendEmailInput } from './send-email.input';
export { SendBulkCampaignInput } from './send-bulk-campaign.input';
export { PolishDraftInput } from './polish-draft.input';
export { PaginationInput } from './pagination.input';
export { EmailDraftConnection, EmailDraftPageInfo } from './email-draft-connection.output';
