name: Test Suite

on:
  push:
    branches: [main, staging, email-composition]
  pull_request:
    branches: [main, staging]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run database package tests
        run: |
          cd packages/database
          pnpm test
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Run API tests
        run: |
          cd apps/api
          pnpm test:ci
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          # Add any required environment variables for testing
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
          JWT_SECRET: test-secret-key-for-ci
          SUPABASE_URL: https://test.supabase.co
          SUPABASE_JWT_SECRET: test-jwt-secret
          SUPABASE_SERVICE_ROLE_KEY: test-service-role-key

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            apps/api/coverage
            packages/database/coverage
          retention-days: 30

      - name: Test Summary
        if: always()
        run: |
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          echo "✅ All tests completed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Packages Tested:" >> $GITHUB_STEP_SUMMARY
          echo "- Database package" >> $GITHUB_STEP_SUMMARY
          echo "- API package" >> $GITHUB_STEP_SUMMARY
